name: hello_flutter_two_dimensional
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  hooks_riverpod: 2.4.9
  logging: 1.2.0
  two_dimensional_scrollables: 0.0.5+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/init_data.json
    - assets/images/floor.png
    - assets/images/rock.png
    - assets/images/wall.png
    - assets/images/path.png
    - assets/images/door.png
    - assets/images/mark_none.png
    - assets/images/mark1.png
    - assets/images/mark2.png
    - assets/images/mark3.png
